services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - pleste-backend
    healthcheck: # https://github.com/peter-evans/docker-compose-healthcheck
      test: [ "CMD-SHELL", "pg_isready", "-d", "pleste" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  pleste-client:
    build:
      context: .
      dockerfile: pleste-client/Dockerfile
      network: tfg_plataforma_xestion_tecnica_pleste-frontend
    ports:
      - "8000:80"
      - "5005:5005"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://pleste-client:80"]
      interval: 15s
    depends_on:
      - pleste-server
    networks:
      - pleste-frontend
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar pleste-client-1.0-SNAPSHOT.jar
  pleste-server:
    build:
      context: .
      dockerfile: pleste-server/Dockerfile
    ports:
      - "5006:5005"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://pleste-server/api/v0/openapi.json"]
      interval: 15s
    depends_on:
      - postgres
    networks:
      - pleste-backend
      - pleste-frontend
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar pleste-server-1.0-SNAPSHOT.jar
volumes:
  postgres-data:
networks:
  pleste-backend:
    internal: true
  pleste-frontend:
    driver: bridge